spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/CHAT_DB
    username: root
    password: 1234

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS256

jwt:
  secret: hJ58MK7-Ih_YKiBYpOIhHLgBThGzcMHMrHbOmUHcOEM

